# Generated by Django 5.0.3 on 2024-04-05 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recored',
            new_name='Record',
        ),
    ]
